---
Name: krakenconfig
---
#Kraken settings
Kraken:
    lossy: true
    wait: true
    dev: false
    ignore_kraked_status: false

#extensions
SiteConfig:
    extensions:
        - KrakenSiteConfigExtension
        
Upload:
    extensions:
        - KrakenUploadExtension       
        
File:
    extensions:
        - KrakenFileExtension
        
Image:
    extensions:
        - KrakenImageExtension
        
AssetAdmin:
    extensions:
        - KrakenAssetAdminExtension
        
Image:
    backend: KrakenGDBackend